/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#6900b3",
        "primary-container": "#9c48ea",
        "tertiary-fixed": "#ffdead",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#eadfed",
        "surface-tint": "#842bd2",
        "primary-fixed-dim": "#ddb7ff",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#07006c",
        "on-primary-fixed": "#2c0051",
        "outline-variant": "#cfc2d6",
        "surface-bright": "#fff7fe",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#fffbff",
        "tertiary-container": "#9b6b00",
        "secondary": "#4648d4",
        "primary": "#8127cf",
        "tertiary": "#7b5500",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#fabc4e",
        "on-primary": "#ffffff",
        "surface-container-low": "#fbf0fe",
        "on-tertiary-fixed-variant": "#604100",
        "surface-dim": "#e1d7e4",
        "surface-container-high": "#f0e5f2",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f8edfb",
        "secondary-fixed": "#e1e0ff",
        "background": "#fff7fe",
        "inverse-surface": "#342e38",
        "outline": "#7e7385",
        "surface-container": "#f5eaf8",
        "secondary-fixed-dim": "#c0c1ff",
        "surface-variant": "#eadfed",
        "primary-fixed": "#f0dbff",
        "on-secondary-fixed-variant": "#2f2ebe",
        "on-background": "#1f1a23",
        "on-tertiary-fixed": "#281900",
        "on-tertiary-container": "#fffbff",
        "error": "#ba1a1a",
        "secondary-container": "#6063ee",
        "surface": "#10131c",
        "on-surface": "#1f1a23",
        "on-surface-variant": "#4d4354",
        "inverse-primary": "#ddb7ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-md": "16px",
        "margin-lg": "32px",
        "container-padding": "24px",
        "unit": "8px",
        "gutter": "16px",
        "margin-sm": "8px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter"],
        "label-zh": ["Inter"],
        "body-sm": ["Inter"],
        "label-en": ["Inter"],
        "headline-md": ["Inter"],
        "data-mono": ["JetBrains Mono"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "headline-lg-mobile": ["28px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "label-zh": ["13px", {"lineHeight": "1", "fontWeight": "500"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "label-en": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "data-mono": ["14px", {"lineHeight": "1.4", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
