// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLog(arg1) {
  return window['go']['main']['App']['AddLog'](arg1);
}

export function IPCInvoke(arg1, arg2) {
  return window['go']['main']['App']['IPCInvoke'](arg1, arg2);
}

export function IPCSend(arg1, arg2) {
  return window['go']['main']['App']['IPCSend'](arg1, arg2);
}

export function IsQuitting() {
  return window['go']['main']['App']['IsQuitting']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function SetQuitting(arg1) {
  return window['go']['main']['App']['SetQuitting'](arg1);
}

export function ShowItemInFolder(arg1) {
  return window['go']['main']['App']['ShowItemInFolder'](arg1);
}
